language: python

matrix:
  include:
    - os: linux
      python: 3.5
      env: TORCH_WHL=http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-linux_x86_64.whl

    - os: linux
      python: 3.6
      env: TORCH_WHL=http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl

install:
  - pip install $TORCH_WHL
  - pip install "tqdm>=4.0"
  - pip install "cvxpy>=0.4,<1.0"
  - pip install cvxopt

script:
  - python -m unittest
